### ISSUE TITLE
About list of Vision, Depth or Camera sensors

### ISSUE THREAD

**Issue by ArghyaChatterjee** [szenergy/awesome-lidar#3]
Hello, I was wondering if you know any opensource repo that lists Vision, Depth or Camera sensors, that would be helpful. 
N.B: You mentioned a great repo: https://github.com/jbhuang0604/awesome-computer-vision but this one does not list sensors.

**Comment by horverno** [comment]
Hello, sorry, I don't know any, the closest to this you can get is: http://wiki.ros.org/Sensors
